---
- hosts: nagios
  remote_user: ansibleuser
  become: yes
  tasks:
    - name: Push configuration code block to hosts.cfg
      blockinfile:
#            dest: /tmp/services_jumpserverclusternew.cfg
            dest: /etc/nagios/objects/services_UatCluster2_50K.cfg
            insertafter: BOF
            backup: yes
            state: present
            block: |
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             PING
                check_command                   check_ping!100.0,20%!500.0,60%
                contact_groups                  admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Root Partition
                check_command                   check_nrpe!check_disk
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             /opt disk
                check_command                   check_nrpe!check_disk_opt
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Current Users
                check_command                   check_nrpe!check_users
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Zombie Processes
                check_command                   check_nrpe!check_zombie_procs
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Current Load
                check_command                   check_nrpe!check_load
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             SSH
                check_command                   check_ssh
                contact_groups                  admins,client
                notifications_enabled           0
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Total Processes
                check_command                   check_nrpe!check_procs
                contact_groups                   admins,client
                }
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             CPU Usage
                check_command                   check_nrpe!check_cpu
                contact_groups                   admins,client
                }               
                define service{
                use                             local-service,srv-pnp
                host_name                       {{ item }}
                service_description             Memory
                check_command                   check_nrpe!check_mem
                notifications_enabled           0
                contact_groups                   admins,client
                }
            marker: "# {mark} ANISBLE MANAGED BLOCK {{item}}"
      with_items: "{{ groups['Newlyadded_uatcl2'] }}"
